name: docs

on:
  push:
    branches:
      - "theme-switch"

jobs:
  build:
    name: Build Documentation
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Additional info about the build
      shell: bash
      run: |
        uname -a
        df -h
        ulimit -a


    # More info on options: https://github.com/conda-incubator/setup-miniconda
    - uses: conda-incubator/setup-miniconda@v2.2.0
      with:
        python-version: 3.11
        environment-file: requirements.yaml

        channels: conda-forge,defaults

        activate-environment: docs
        auto-update-conda: false
        auto-activate-base: false
        show-channel-urls: true

    - name: Build HTML
      shell: bash -l {0}
      run: |
        cd _episodes/
        make html

    - name: Deploy Documentation
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        folder: _episodes/_build/html
